const COPY = {
  ko: {
    tab: "멤버별 보드", title: "멤버별 보드", intro: "메모리 보유 수와 멤버별 노드·커넥트 배치를 관리하세요.",
    preview: "UI 미리보기", notice: "현재는 공통 참조 배치(tree-model-001)로 조작을 확인하는 화면입니다. 멤버별 실제 보드·효과·해금 조건의 데이터 동기화와 점수 계산 반영은 다음 단계입니다. 입력은 미리보기 전용으로 저장됩니다.",
    memory: "메모리 보유 개수", memoryHint: "계정 공통 입력 · 비워 두면 미입력 · 보너스 계산은 동기화 후 연결", memoryPlaceholder: "미입력",
    search: "멤버 검색", all: "전체", configured: "입력됨", unconfigured: "미입력", filter: "입력 상태", production: "소속", noMembers: "조건에 맞는 멤버가 없습니다.",
    count: "{count}명", summary: "선택 {nodes}칸 · 커넥트 {slots}/4", back: "멤버 목록", export: "내보내기", import: "가져오기", saved: "이 브라우저에 저장했습니다.",
    reference: "공통 참조 보드 · 실제 멤버별 모델 연결 전", R: "리더", B: "멤버", G: "전체 서포트", Y: "콘텐츠 서포트", S: "커넥트",
    zoomIn: "확대", zoomOut: "축소", fit: "전체 보기", grid: "보드 보기", list: "목록 보기", node: "노드", selected: "선택됨", locked: "미선택",
    selectNode: "노드를 선택하면 상세 정보를 확인할 수 있습니다.", toggleOn: "이 칸 선택", toggleOff: "이 칸 선택 해제", effectPending: "효과와 조건 정보는 데이터 동기화 후 표시합니다. 현재 선택은 인게임 해금 가능 여부를 검증하지 않습니다.",
    chooseCard: "보유카드 선택", changeCard: "카드 변경", noCard: "배치된 카드 없음", unlockFirst: "커넥트 칸을 먼저 선택한 뒤 카드를 배치하세요.",
    reset: "이 보드 초기화", resetAsk: "이 멤버의 노드 선택과 커넥트 배치를 초기화할까요?", unlockAsk: "이 칸 선택을 해제하면 배치 카드도 해제됩니다. 계속할까요?",
    pickerTitle: "커넥트 카드 선택", pickerHint: "내 보유카드만 표시합니다. 다른 보드·슬롯의 사용 위치를 확인하고 이동할 수 있습니다. 같은 카드의 중복 배치는 허용하지 않습니다.",
    close: "닫기", cardSearch: "멤버명 또는 카드명 검색", rarity: "레어도", availableOnly: "배치 가능한 카드만", available: "배치 가능", current: "현재 슬롯", used: "사용 중: {where}",
    cardSetting: "Lv.{level} · {potential}개화", cardsShown: "{count}장 표시", noOwned: "등록된 보유카드가 없습니다. 먼저 보유카드를 등록하세요.", noCards: "조건에 맞는 보유카드가 없습니다.", goOwned: "보유카드 등록", remove: "배치 해제",
    moveAsk: "{card}를 {from}에서 {to}(으)로 이동할까요? 기존 슬롯은 비워집니다.", replaceAsk: "대상 슬롯의 {card} 배치는 해제됩니다.", confirm: "확인 후 배치", cancel: "취소",
    imported: "보드 미리보기 정보를 가져왔습니다.", importAsk: "가져온 파일로 보드 미리보기와 메모리 입력을 교체할까요? 보유카드 목록은 변경하지 않습니다.",
    ownershipChanged: "보유 해제된 카드의 커넥트 배치를 해제했습니다.", loading: "보드 화면을 불러오는 중…", retry: "다시 시도", loadError: "보드 화면을 불러오지 못했습니다. 다른 메뉴는 계속 사용할 수 있습니다.",
    error: "변경을 적용하지 못했습니다. 입력 또는 저장 상태를 확인하세요.", INVALID_MEMORY_COUNT: "메모리 개수는 0 이상의 정수로 입력하세요.",
    INVALID_BOARD_FILE: "지원하지 않는 보드 파일입니다. 형식·버전·멤버 정보를 확인하세요.", INVALID_NODE: "지원하지 않는 노드입니다.", INVALID_SLOT: "유효하지 않은 커넥트 슬롯입니다.", INVALID_CARD: "카드 정보가 올바르지 않습니다.",
    DUPLICATE_CARD: "파일에 동일 카드의 중복 배치가 있습니다. 기존 입력은 유지됩니다.", CARD_NOT_OWNED: "보유하지 않은 카드는 배치할 수 없습니다. 보유카드를 먼저 등록하세요.", SLOT_LOCKED: "커넥트 칸을 먼저 선택하세요.", CARD_IN_USE: "다른 슬롯에서 사용 중입니다. 배치 위치를 확인하고 다시 선택하세요.", PLACEMENT_CHANGED: "배치 상태가 변경되었습니다. 목록을 확인하고 다시 선택하세요.",
    STORAGE_READ_FAILED: "저장 정보를 읽지 못했습니다. 기존 파일은 덮어쓰지 않았습니다. 정상 백업 파일을 가져와 복구하세요.", STORAGE_WRITE_FAILED: "브라우저 저장소에 저장하지 못했습니다. 저장 권한과 남은 공간을 확인하세요.",
  },
  en: {
    tab: "Member Boards", title: "Member Boards", intro: "Manage your memory count, board nodes and Connect placements.",
    preview: "UI PREVIEW", notice: "This UI uses a shared reference layout (tree-model-001). Actual per-member boards, effects, unlock rules, data sync and scoring integration are deferred. Changes are saved in a separate preview profile.",
    memory: "Owned memories", memoryHint: "Account-wide · blank means unset · bonus calculation is not connected yet", memoryPlaceholder: "Not entered",
    search: "Search members", all: "All", configured: "Configured", unconfigured: "Not entered", filter: "Input status", production: "Production", noMembers: "No matching members.", count: "{count} members", summary: "{nodes} nodes · Connect {slots}/4", back: "Member list", export: "Export", import: "Import", saved: "Saved in this browser.",
    reference: "Shared reference board · not the member-specific model", R: "Leader", B: "Member", G: "Global support", Y: "Content support", S: "Connect", zoomIn: "Zoom in", zoomOut: "Zoom out", fit: "Fit board", grid: "Board view", list: "List view", node: "Node", selected: "Selected", locked: "Unselected",
    selectNode: "Select a node to view its details.", toggleOn: "Select this node", toggleOff: "Unselect this node", effectPending: "Effects and conditions will be available after data sync. Selection does not validate in-game unlock eligibility.", chooseCard: "Choose owned card", changeCard: "Change card", noCard: "No card placed", unlockFirst: "Select the Connect node before placing a card.", reset: "Reset this board", resetAsk: "Reset this member's node selections and Connect placements?", unlockAsk: "Unselecting this node also removes its card. Continue?",
    pickerTitle: "Choose a Connect card", pickerHint: "Only owned cards are shown. See each card's existing board/slot and confirm a move. A card cannot occupy more than one slot.", close: "Close", cardSearch: "Search member or card name", rarity: "Rarity", availableOnly: "Available cards only", available: "Available", current: "Current slot", used: "In use: {where}", cardSetting: "Lv.{level} · Awakening {potential}", cardsShown: "{count} cards", noOwned: "No owned cards registered. Add cards first.", noCards: "No matching owned cards.", goOwned: "Register owned cards", remove: "Remove card", moveAsk: "Move {card} from {from} to {to}? The old slot will be cleared.", replaceAsk: "The target slot's {card} will be removed.", confirm: "Confirm placement", cancel: "Cancel", imported: "Board preview imported.", importAsk: "Replace the board preview and memory count with this file? Owned cards will not change.", ownershipChanged: "Removed Connect placements for cards no longer owned.", loading: "Loading boards…", retry: "Retry", loadError: "Could not load the board view. Other tabs remain available.",
    error: "Could not apply the change. Check the input and browser storage.", INVALID_MEMORY_COUNT: "Enter a non-negative whole number.", INVALID_BOARD_FILE: "Unsupported board file, version or member data.", INVALID_NODE: "Unsupported node.", INVALID_SLOT: "Invalid Connect slot.", INVALID_CARD: "Invalid card.", DUPLICATE_CARD: "The file assigns a card more than once. Existing input is unchanged.", CARD_NOT_OWNED: "Register this card as owned before placing it.", SLOT_LOCKED: "Select the Connect node first.", CARD_IN_USE: "The card is in use elsewhere. Check its current location.", PLACEMENT_CHANGED: "Placement changed. Check the list and choose again.", STORAGE_READ_FAILED: "Could not read saved data. It was not overwritten. Import a valid backup to recover.", STORAGE_WRITE_FAILED: "Could not save. Check browser storage permissions and free space.",
  },
  ja: {
    tab: "ホロメンボード", title: "ホロメンボード", intro: "メモリー所持数とノード・コネクト配置を管理します。", preview: "UIプレビュー", notice: "共通の参考配置(tree-model-001)による操作プレビューです。ホロメン別の実際のボード・効果・解放条件、データ同期、スコア反映は次の段階です。入力はプレビュー専用に保存されます。",
    memory: "メモリー所持数", memoryHint: "アカウント共通・空欄は未入力・ボーナス計算は未接続", memoryPlaceholder: "未入力", search: "ホロメン検索", all: "すべて", configured: "入力済み", unconfigured: "未入力", filter: "入力状態", production: "所属", noMembers: "該当するホロメンがいません。", count: "{count}人", summary: "選択 {nodes}マス・コネクト {slots}/4", back: "一覧へ", export: "エクスポート", import: "インポート", saved: "このブラウザーに保存しました。", reference: "共通参考ボード・ホロメン別モデルは未接続", R: "リーダー", B: "メンバー", G: "全体サポート", Y: "コンテンツサポート", S: "コネクト", zoomIn: "拡大", zoomOut: "縮小", fit: "全体表示", grid: "ボード表示", list: "一覧表示", node: "ノード", selected: "選択済み", locked: "未選択", selectNode: "ノードを選択すると詳細を表示します。", toggleOn: "このマスを選択", toggleOff: "選択を解除", effectPending: "効果・条件はデータ同期後に表示します。ゲーム内の解放条件は検証しません。", chooseCard: "所持カードを選択", changeCard: "カード変更", noCard: "カード未配置", unlockFirst: "コネクトマスを選択してからカードを配置してください。", reset: "このボードをリセット", resetAsk: "このホロメンのノード選択とコネクト配置をリセットしますか？", unlockAsk: "選択を解除すると配置カードも外れます。続けますか？", pickerTitle: "コネクトカード選択", pickerHint: "所持カードだけを表示します。使用中のボード・枠を確認して移動できます。同じカードの重複配置はできません。", close: "閉じる", cardSearch: "ホロメン名・カード名を検索", rarity: "レア度", availableOnly: "配置可能なカードのみ", available: "配置可能", current: "現在の枠", used: "使用中: {where}", cardSetting: "Lv.{level}・開花 {potential}", cardsShown: "{count}枚", noOwned: "所持カードが未登録です。先に登録してください。", noCards: "該当する所持カードがありません。", goOwned: "所持カード登録", remove: "配置解除", moveAsk: "{card}を{from}から{to}へ移動しますか？元の枠は空になります。", replaceAsk: "移動先の{card}は外れます。", confirm: "確認して配置", cancel: "キャンセル", imported: "プレビューをインポートしました。", importAsk: "ボードプレビューとメモリー数をこのファイルで置き換えますか？所持カードは変更しません。", ownershipChanged: "所持解除されたカードの配置を解除しました。", loading: "ボードを読み込み中…", retry: "再試行", loadError: "ボードを読み込めませんでした。他のタブは利用できます。", error: "変更できませんでした。入力・保存状態を確認してください。", INVALID_MEMORY_COUNT: "0以上の整数を入力してください。", INVALID_BOARD_FILE: "未対応の形式・バージョン・ホロメン情報です。", INVALID_NODE: "未対応のノードです。", INVALID_SLOT: "無効な枠です。", INVALID_CARD: "無効なカードです。", DUPLICATE_CARD: "カードの重複配置があります。元の入力は保持されます。", CARD_NOT_OWNED: "先に所持カードを登録してください。", SLOT_LOCKED: "コネクトマスを先に選択してください。", CARD_IN_USE: "別の枠で使用中です。配置を確認してください。", PLACEMENT_CHANGED: "配置が変更されました。確認して選び直してください。", STORAGE_READ_FAILED: "保存情報を読み込めません。上書きせず保持しました。正常なバックアップをインポートしてください。", STORAGE_WRITE_FAILED: "保存できません。保存権限と空き容量を確認してください。",
  },
};
export function boardText(locale, key, args = {}) {
  return String(DATA_COPY[locale]?.[key] ?? DATA_COPY.ko[key] ?? COPY[locale]?.[key] ?? COPY.ko[key] ?? COPY.ko.error)
    .replace(/\{(\w+)\}/g, (_, name) => String(args[name] ?? ""));
}

// Master-backed copy overrides the historical preview labels without changing navigation.
const DATA_COPY = {
  ko: {
    selectAll: '일괄 선택', removeAll: '일괄 해제', categorySelectTitle: '{category} 일괄 선택', categoryRemoveTitle: '{category} 일괄 해제',
    categorySelectAsk: '{category}의 모든 칸을 연결하도록 총 {count}칸을 선택할까요?', categoryRemoveAsk: '{category}의 선택된 칸과 연결이 끊기는 칸까지 총 {count}칸을 해제할까요?',
    categoryExtraSelect: '연결 경로에 필요한 다른 분류의 {count}칸도 포함됩니다.', categoryExtraRemove: '시작점과 연결이 끊기는 다른 분류의 {count}칸도 포함됩니다.',
    routeTitle: '최단 경로 선택', routeAsk: '{node}까지 연결하는 {count}칸을 함께 선택할까요?', confirmSelect: '함께 선택',
    disconnectTitle: '연결된 칸 해제', disconnectAsk: '{node}을 해제하면 시작점과 연결되지 않는 칸까지 총 {count}칸이 해제됩니다. 계속할까요?', confirmRemove: '함께 해제',
    removedCards: '함께 해제되는 커넥트 카드', moveTitle: '커넥트 카드 이동', replaceTitle: '커넥트 카드 교체',
    BOARD_PATH_UNAVAILABLE: '시작점에서 연결되는 경로를 찾을 수 없습니다.', BOARD_PATH_CHANGED: '보드 상태가 바뀌었습니다. 경로를 다시 확인해 주세요.',
    preview: '멤버별 보드', notice: '선택한 노드·커넥트·메모리를 점수 계산에 반영합니다.',
    goDeck: '편성으로 돌아가기', export: 'JSON 내보내기', import: 'JSON 가져오기',
    allProductions: '소속 전체', allStates: '입력 상태 전체',
    memoryHint: '전체 멤버에게 적용됩니다.',
    summary: '선택 {nodes}칸 · 커넥트 {slots}/{total}',
    boardUnavailable: '보드 데이터 없음', unavailableDetail: '현재 Master에 이 멤버의 보드 모델 참조가 없습니다. 다른 멤버의 보드로 대체하지 않습니다.',
    memoryBonus: '메모리 파라미터 보너스 +{value}%', memoryUnset: '메모리 개수 미입력',
    memoryUnknown: '현재 표는 {max}개까지 확인됩니다. 초과 수량의 보너스는 추정하지 않습니다.',
    connectLevel: 'Lv.{level}', connectUnavailable: '커넥트 효과 데이터 없음', rangeCells: '원본 상대 범위 {count}칸 · 중심은 커넥트 슬롯',
    pointCost: '보드 Pt', materials: '소모 재료', viewCondition: '표시 조건', unlockCondition: '해금 조건',
    recordOnly: '실제 해금 상태를 기록하는 기능입니다. 보유 재료·포인트와 선행 경로는 검사하지 않습니다.',
    rangeNote: '범위 안의 노드에는 현재 개화 단계의 커넥트 강화율을 적용합니다.',
    migrate: '이전 미리보기 입력 가져오기', noPreview: '이 브라우저에 이전 미리보기 입력이 없습니다.',
    migrateAsk: '미리보기에서 {count}명의 보드를 노드 ID 기준으로 옮깁니다. 실제 위치와 효과를 다시 확인하세요. 이전 원본은 유지되며 현재 보드 프로필은 교체됩니다. 이전할 수 없는 항목: {issues}건. 계속할까요?',
    imported: '보드 프로필을 가져왔습니다.', importAsk: '보드 프로필과 메모리 개수를 이 파일로 교체할까요? 보유카드는 변경하지 않습니다.',
    BOARD_PROFILE_REVIEW: '저장된 보드가 현재 Master와 일치하지 않습니다. 원본은 보존했습니다. 레이아웃·노드 정보를 검토한 백업을 가져와 주세요.',
  },
  en: {
    selectAll: 'Select all', removeAll: 'Deselect all', categorySelectTitle: 'Select all: {category}', categoryRemoveTitle: 'Deselect all: {category}',
    categorySelectAsk: 'Select {count} cells to connect all {category} cells?', categoryRemoveAsk: 'Deselect {count} cells, including selected {category} cells and cells disconnected from the start?',
    categoryExtraSelect: 'Includes {count} cells of other categories needed for the routes.', categoryExtraRemove: 'Includes {count} cells of other categories disconnected from the start.',
    routeTitle: 'Select shortest route', routeAsk: 'Select {count} cells to connect {node} to the start?', confirmSelect: 'Select cells',
    disconnectTitle: 'Deselect disconnected cells', disconnectAsk: 'Removing {node} will deselect {count} cells, including cells disconnected from the start. Continue?', confirmRemove: 'Deselect cells',
    removedCards: 'Connect cards to remove', moveTitle: 'Move Connect card', replaceTitle: 'Replace Connect card',
    BOARD_PATH_UNAVAILABLE: 'No route from the start was found.', BOARD_PATH_CHANGED: 'The board has changed. Please review the route again.',
    preview: 'Member boards', notice: 'Selected nodes, Connect cards and memories are included in score calculations.',
    goDeck: 'Back to formation', export: 'Export JSON', import: 'Import JSON',
    allProductions: 'All branches', allStates: 'All statuses',
    memoryHint: 'Applies to all members.',
    summary: '{nodes} nodes · Connect {slots}/{total}',
    boardUnavailable: 'No board data', unavailableDetail: 'This Master has no board model reference for this member. Another member’s board is not substituted.',
    memoryBonus: 'Memory stat bonus +{value}%', memoryUnset: 'Memory count not entered',
    memoryUnknown: 'The source table covers up to {max} memories. Bonuses beyond it are not extrapolated.',
    connectLevel: 'Lv.{level}', connectUnavailable: 'No Connect effect data', rangeCells: '{count} source-relative cells · origin is the Connect slot',
    pointCost: 'Board points', materials: 'Materials', viewCondition: 'Visibility condition', unlockCondition: 'Unlock condition',
    recordOnly: 'Record already unlocked nodes. Materials, point budgets and prerequisite paths are not enforced.',
    rangeNote: 'Nodes in range use the Connect boost for the card’s current awakening level.',
    migrate: 'Import old UI preview', noPreview: 'No old UI preview exists in this browser.',
    migrateAsk: 'Convert {count} preview boards by node ID? Recheck actual positions and effects. The old preview is preserved; the current board profile will be replaced. Unmappable entries: {issues}. Continue?',
    imported: 'Board profile imported.', importAsk: 'Replace this board profile and memory count? Owned cards will not change.',
    BOARD_PROFILE_REVIEW: 'The saved board does not match this Master. The original is preserved. Review its layout and nodes before importing a compatible backup.',
  },
  ja: {
    selectAll: '一括選択', removeAll: '一括解除', categorySelectTitle: '{category}を一括選択', categoryRemoveTitle: '{category}を一括解除',
    categorySelectAsk: '{category}の全マスをつなぐため、合計{count}マスを選択しますか？', categoryRemoveAsk: '{category}の選択済みマスと接続が切れるマスを含む、合計{count}マスを解除しますか？',
    categoryExtraSelect: '経路に必要な他の分類の{count}マスも含まれます。', categoryExtraRemove: '開始点との接続が切れる他の分類の{count}マスも含まれます。',
    routeTitle: '最短経路を選択', routeAsk: '{node}を開始点につなぐ{count}マスをまとめて選択しますか？', confirmSelect: 'まとめて選択',
    disconnectTitle: '接続が切れるマスを解除', disconnectAsk: '{node}を解除すると、開始点につながらなくなるマスを含め{count}マスが解除されます。続けますか？', confirmRemove: 'まとめて解除',
    removedCards: '同時に外れるコネクトカード', moveTitle: 'コネクトカードを移動', replaceTitle: 'コネクトカードを交換',
    BOARD_PATH_UNAVAILABLE: '開始点からの経路が見つかりません。', BOARD_PATH_CHANGED: 'ボードの状態が変わりました。経路を再確認してください。',
    preview: 'ホロメンボード', notice: '選択したノード・コネクト・メモリーをスコア計算に反映します。',
    goDeck: '編成に戻る', export: 'JSONを書き出す', import: 'JSONを読み込む',
    allProductions: '所属すべて', allStates: '入力状態すべて',
    memoryHint: 'すべてのホロメンに適用されます。',
    summary: '選択 {nodes}マス・コネクト {slots}/{total}',
    boardUnavailable: 'ボードデータなし', unavailableDetail: '現在のMasterにはこのホロメンのボードモデル参照がありません。他のモデルで代用しません。',
    memoryBonus: 'メモリーパラメータボーナス +{value}%', memoryUnset: 'メモリー数は未入力',
    memoryUnknown: '現在の表は{max}個までです。範囲外のボーナスは推定しません。',
    connectLevel: 'Lv.{level}', connectUnavailable: 'コネクト効果データなし', rangeCells: '相対範囲{count}マス・中心はコネクト枠',
    pointCost: 'ボードPt', materials: '消費素材', viewCondition: '表示条件', unlockCondition: '解放条件',
    recordOnly: '解放済み状態を記録します。素材・Pt・前提経路は検証しません。',
    rangeNote: '範囲内のノードには現在の開花段階のコネクト強化率を適用します。',
    migrate: '以前のプレビューを取り込む', noPreview: 'このブラウザーに以前のプレビューがありません。',
    migrateAsk: 'プレビューの{count}人をノードIDで移行します。実際の位置と効果を確認してください。元データは残り、現在のプロファイルを置き換えます。移行不可: {issues}件。続けますか？',
    imported: 'ボードプロファイルを取り込みました。', importAsk: 'ボードプロファイルとメモリー数を置き換えますか？所持カードは変更しません。',
    BOARD_PROFILE_REVIEW: '保存ボードと現在のMasterが一致しません。元データは保持しています。配置・ノードを確認したバックアップを取り込んでください。',
  },
};
